version: '3.7'

services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - personal

networks:
    personal:
        driver: bridge

volumes:
    db:
        driver: local